### ISSUE TITLE
ReferenceError: Unknown plugin "transform-runtime" specified 

### ISSUE THREAD

**Issue by oovz** [el-jacko/vue-editortable#5]
Get from npm, imported locally, got this error.
```
ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vue-editortable/src/components/VueEditortable.vue
Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified
```

**Comment by el-jacko** [comment]
Hi,

this is a webpack/ babel configuration issue.
It works with vue-cli. If you use something different, you have to change your configuration a bit.

I googled this issue, this is what i found:
Check if the following packages are installed, if not install them:
```
npm install --save-dev babel-plugin-transform-runtime
npm install --save-dev babel-preset-stage-2
npm install --save-dev babel-preset-es2015
```

Check your .babelrc file for:
`"presets": ["es2015"]`
or/and
`"plugins": ["transform-runtime"]`

Let me know if this solved your problem.

By the way, i'm working a lot on this component, i revised the complete component but i'm not finished and the changes aren't committed yet. Hope to finish it in the next couple of weeks.
Cheers
